package Test;

import java.util.Scanner;

class Num extends Exception{
	
	
}

public class A0613_tryCatch {

	public static void main(String[] args) {
		System.out.println("양수 입력");
		
		try {
			int n = in(); //예외가 발생 할 수도 있는 코드
			System.out.println(n);
		}
		catch(Exception e) {
			System.out.println(e.getMessage());
		}
		

	}
	public static int in() throws Num {
		Scanner sc = new Scanner(System.in);
		int input = sc.nextInt();
		
		if(input<0) {
			Num num = new Num();
			throw num;
		}
		return input;
	}

}
